name: Pull Request Pipeline

on:
  push:
    branches-ignore:
      - main

jobs:
  build-and-test-pipeline:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build & Test
        run: ./gradlew clean build

      - name: Spotless Check
        run: ./gradlew spotlessCheck